baseURL = "https://xuana.netlify.com"
title = "xuana online"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "Â© xu 2020 <a href='https://github.com/siegerts/hugo-theme-basic'>Hugo Theme Basic</a>. Made by <a href='https://twitter.com/siegerts'>@siegerts</a>."
description = "xuana is a tech consultant"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "siegerts"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
